値を平均して取得する機能の実装
Sereno-Anan/SerenoDevice pull request #16
Opened 2021-12-08 08:43 UTC by satokitakata

## Issueへのリンク

resolve: #15

## やったこと

センサの値を平均して取得する機能を追加した。

## 変更内容

見えるところの変更なし

## やらないこと

なし

## できるようになること

### ユーザー目線
より正確な情報を知ることができる。

### 開発者目線
より正確な値を取得することができる。

## できなくなること（ユーザ・開発者 目線）

### ユーザー目線
なし

### 開発者目線
なし

## 動作確認

実際にセンサで値を取得し、SheetDBに値を返した。結果は触れているときは1、触れていないときは0が返された。

## その他

なし

## チェックリスト

- [x] タイトルをちゃんと設定できている
- [x] Assignerの設定ができている
- [x] Linked issuesの設定ができている
- [x] Milestoneの設定ができている
- [x] Projects(In Progress)が設定できている
- [x] Reviewerが設定できている

2021-12-08 09:08 UTC, nemuki commented
これ一瞬で終わりません？
ちょっと保留にさせてください〜

2021-12-09 09:04 UTC, nemuki commented
コミットメッセージしっかりするのと、RTCを使って欲しいところ

2021-12-09 09:06 UTC, satokitakata commented
了解しました。

2021-12-11 08:45 UTC, satokitakata commented
このプログラムを実行しても、SheetDBに値が返りませんでした。コードが間違っているのでしょうか？

2021-12-11 09:26 UTC, satokitakata commented
すいません、WiFiのパスワードを間違っていました。今試してみたところちゃんと動作しました。

2021-12-11 10:03 UTC, nemuki requested changes
しゃす

2021-12-11 10:03 UTC, nemuki commented on src/main.cpp
> -  if ((millis() - sendDataPrevMillis > 15000 || sendDataPrevMillis == 0))
これ消されると面倒なのと、SheetDB本番では使わないので復活を

2021-12-11 10:03 UTC, nemuki commented on src/sensor.cpp
> +    endTime = time(NULL) + 30;
```suggestion
    endTime = time(NULL) + measureTime;
```
変数で変更できるようにしてもらえるとわかりやすいかと

2021-12-11 10:10 UTC, satokitakata commented
了解しました

2021-12-11 10:47 UTC, nemuki commented
修正終わってます？

2021-12-11 10:50 UTC, satokitakata commented
終わってます！

2021-12-11 10:51 UTC, nemuki commented
Re review requestおわすれなく

2021-12-11 10:59 UTC, satokitakata commented
了解です

2021-12-11 11:00 UTC, nemuki approved these changes
:yoshi:

2021-12-11 11:00 UTC, merged